{'dataset_name': 'REDDIT-MULTI-12K', 'seed': 777, 'num_workers': 1, 'cov_weight': 0.0001, 'hyperparams': {'batch_size': 64, 'epochs': 701, 'learning_rate': 0.001, 'step_size': 50, 'decay_rate': 0.75}, 'architecture': {'layers': 4, 'hidden': 128, 'pooling': 'add', 'JK': 'last', 'nonlinear_conv': 'G', 'dropout': 0.5, 'variants': {'BN': 'Y'}}, 'commit_id': '7a2fe7c5b74586b179b4778a2646ef97afab9176', 'time_stamp': '1610362700', 'directory': '../../nlg_results/tu/board/'}
-------- FOLD0 DATASET=REDDIT-MULTI-12K, COMMIT_ID=7a2fe7c5b74586b179b4778a2646ef97afab9176
Epoch: 001, Train Loss: 13.6135379, Train Acc: 0.2557750, Test Acc: 0.2632020, Train Cov: 4.4463263
Epoch: 002, Train Loss: 2.6369209, Train Acc: 0.2840909, Test Acc: 0.2766136, Train Cov: 4.4648414
Epoch: 003, Train Loss: 2.1022524, Train Acc: 0.3300112, Test Acc: 0.3436714, Train Cov: 4.4707475
Epoch: 004, Train Loss: 1.9935700, Train Acc: 0.3670827, Test Acc: 0.3679799, Train Cov: 4.4738116
Epoch: 005, Train Loss: 1.9659922, Train Acc: 0.3789121, Test Acc: 0.3671417, Train Cov: 4.4768901
Epoch: 006, Train Loss: 1.9379539, Train Acc: 0.3817064, Test Acc: 0.3654652, Train Cov: 4.4826016
Epoch: 007, Train Loss: 1.8982481, Train Acc: 0.3488264, Test Acc: 0.3419950, Train Cov: 4.4806657
Epoch: 008, Train Loss: 1.8854865, Train Acc: 0.3885060, Test Acc: 0.3830679, Train Cov: 4.4805779
Epoch: 009, Train Loss: 1.8539773, Train Acc: 0.4017325, Test Acc: 0.3864208, Train Cov: 4.4817519
Epoch: 010, Train Loss: 1.8244066, Train Acc: 0.4158905, Test Acc: 0.4107293, Train Cov: 4.4786916
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 456, in accept
    answer_challenge(c, self._authkey)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
