{'dataset_name': 'salicylic_acid', 'seed': 666, 'num_workers': 1, 'cov_weight': 0, 'hyperparams': {'batch_size': 128, 'epochs': 1001, 'learning_rate': 0.001, 'step_size': 50, 'decay_rate': 0.75}, 'architecture': {'layers': 4, 'hidden': 128, 'pooling': 'add', 'JK': 'cat', 'method': 'penalty', 'dropout': 0.5, 'exps': 1, 'nonlinear': 'LeakyR0.2', 'aggr': 'add', 'BN': 'N'}, 'commit_id': '09c7fdcf9e91bfcc0fcf535ce1b0d71f54b30449', 'time_stamp': '1613448941', 'directory': '../../nlg_results/pca/board/'}
Downloading http://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/salicylic_acid.zip
Traceback (most recent call last):
  File "./main.py", line 282, in <module>
    main()
  File "./main.py", line 272, in main
    dataset = get_dataset(config.dataset_name).shuffle()
  File "./main.py", line 35, in get_dataset
    dataset = TUDataset(path, name)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/datasets/tu_dataset.py", line 66, in __init__
    pre_filter)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 90, in __init__
    self._download()
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 142, in _download
    self.download()
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/datasets/tu_dataset.py", line 128, in download
    path = download_url('{}/{}.zip'.format(url, self.name), folder)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/download.py", line 31, in download_url
    data = urllib.request.urlopen(url)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
